### ISSUE TITLE
Corriger les erreurs Segmonto / HTRVX sur les données déjà déposées

### ISSUE THREAD

**Issue by PonteIneptique** [HTR-United/CREMMA-MSS-18#17]
Suite à un bug, HTRVX ne "plantait" pas les tests avant la version 0.0.7. Il y a donc des données déjà déposées qui sont invalides et qui planteront les tests.

@CollapsarIsReal pouvez-vous "nettoyer" l'abrégé ?

**Comment by ElsaVK** [comment]
Bonjour,
Je m'en occupe !

**Comment by PonteIneptique** [comment]
Il s'avère que tout va bien en fait...

**Comment by PonteIneptique** [comment]
Vous aviez donc fait du très bon travail !

**Comment by ElsaVK** [comment]
AH. Bon bah tant mieux, merci :)
