### ISSUE TITLE
Problème de GraphicZone

### ISSUE THREAD

**Issue by ElsaVK** [HTR-United/CREMMA-MSS-18#21]
Bonjour,

Je suis confronté à une page avec des dessins réalisés à la main, au centre de la page. Chaque dessin porte une légende. Voici la page en question :
![121_ZoneDessin2](https://user-images.githubusercontent.com/92538363/157324070-2fee65f3-206f-495e-8ed9-453a2982c5c6.png)

Comment traiter cette particularité ? Pour l'instant j'ai fait une MainZone qui prend toute la page, avec des GraphicZone vides pour chaque dessin. Mais ça ne passe pas les test au moment de la PR...De plus, mes titres sont reliés à la MainZone, et ne sont que des DefaultLine. Peut-être devrais-je plutôt les indiquer comme étant HeadingLine:rubric ?

Si quelqu'un a une idée pour m'aiguiller, je suis preneuse :)
Merci !

**Comment by PonteIneptique** [comment]
Je mettrais des HeadingLine dans les zones de dessins sans zone Main

CC @gabays ?

**Comment by gabays** [comment]
On a trop peu pensé à cette question, à laquelle je me suis trouvé confronté la semaine dernière. Ma solution perso (qui n'est pas validée par mes collègues de SegmOnto) a été:
* des `HeadingLine` si c'est une légende
* des `DefaultLine` si c'est du texte dans l'image

C'est à vous de définir le statut du texte et d'annoter en fonction de votre décision.

**Comment by ElsaVK** [comment]
Très bien, je suivre vos exemples et mettre des HeadingLine liés à chaque GraphicZone. Je vous remercie !
