### ISSUE TITLE
Problèmes transcription

### ISSUE THREAD

**Issue by ElsaVK** [HTR-United/CREMMA-MSS-18#8]
Bonjour à tous.tes,

J'ai quelques soucis pour certaines situations rencontrées lors de mes alignements. Pourriez-vous m'indiquer comment traiter ces différents problèmes ? Vous trouverez des captures d'écran en guise d'exemple pour chacun des questionnements.

1 : Dois-je mettre les titres en _DropCapitalLine_ ou alors simplement en _DefaultLine_, ignorant le fait qu'ils soient écrits avec des lettres plus grosses que les lignes normales ?
![39_ligneCapitale](https://user-images.githubusercontent.com/92538363/154360588-d5fe74bf-4fd7-4e29-904e-1bdfabc0b45f.png)

2: Que faire si je rencontre des mots que je ne parviens pas à transcrire ?
![43_motIncompris](https://user-images.githubusercontent.com/92538363/154360703-e2c9b333-ca27-421a-a7fb-4ed7b8454794.png)

3: Que dois-je mettre pour les abbréviations ?
![47_abreviations](https://user-images.githubusercontent.com/92538363/154360940-4c274a90-ed4f-4c74-938c-63927f729d95.png)
![49_abbreviations](https://user-images.githubusercontent.com/92538363/154361111-a0e0d239-8c48-452d-8f68-b99292c30737.png)

4: Dernière chose, que dois-je mettre pour les fins de mots écrites en exposant ?
![55_motExposant](https://user-images.githubusercontent.com/92538363/154362218-456f5505-e151-4c80-a687-62a83349bfcc.png)

Merci à vous tous.tes !

**Comment by PonteIneptique** [comment]
Après question aux gestionnaires Segmonto:

1. Il s'agit d'une [HeadingLine](https://github.com/SegmOnto/Guidelines/blob/main/lines/HeadingLine/HeadingLine.md) et non d'une DropCapital. Cela veut dire qu'il n'a besoin que d'une zone, mais il faut séparer les deux lignes en DefaultLine et HeadingLine.
2. Je passe
3. @alix-tz Je pense que dans ce cadre, 
  1. Pour les exposants, on peut faire un ^t^ et ^ent^, qu'en penses-tu ?
  2. On conserve l'original, donc `&` si je lis bien (rien de promis)
4. Cf. 3.

**Comment by PonteIneptique** [comment]
Ps. pensez à mettre le lien vers la page

**Comment by gabays** [comment]
- Dans le premier cas je lis _n'entre_ mais sans la page complète c'est difficile.
- Pour les abréviations, il faut distinguer une abréviation par contraction (_Mme_ pour _M(adam)e_) des abrévéiations par suspension (_hab._ pour _hab(itant)_). Il y a celle avec ou sans _titulus_. Il n'existe pas de solution générale standard.
   - Plus concrètement, dans le cas de vos abréviations par contraction avec lettres suscrites (le 3.a et 4.), je recommanderais de ne pas développer l'abréviation, et d'indiquer la partie suscrite en la signalant avec un signe du type `^` -> `^t` et `^ent` (pas forcément l'idéal, mais ça permet de la retrouver). Comme elle est en fin de mot, inutile de la refermer  avec `^t^` (ça fait un truc de plus à apprendre à la machine… J'avais eu des problèmes par le passé en utilisant des chevrons: faut être minimal).
   - Pour l'esperluette (3b), on la garde bien sûr. Plus généralement, pour les caractères spéciaux, on suit la [MUFI](https://mufi.info/m.php?p=mufichar) si on peut.
- Pour la question sur SegmOnto, c'est effectivement une `HeadingLine` dans une `MainZone`. Là encore: faisons simple, pour nous mais aussi pour la machine. D'expérience la multiplication des zones marche mal, car elle requiert bien plus de données

**Comment by ElsaVK** [comment]
Merci à tous les deux pour vos réponses, je vais de ce pas rectifier tout ça.

**Comment by alix-tz** [comment]
Bonjour,
Je rejoins Simon concernant le signalement des abréviations, inutile de placer un `^` pour "fermer" la portion suscrite car ça ne marche pas vraiment ensuite. 
Pour aller plus loin, on peut poser la question de savoir comment traiter les cas où plusieurs mots sont mis à la suite en forme suscrite. Avec `M^me Bidule` en fait on suppose toujours que l'espace marque la fin de la portion suscrite. Donc si on a plusieurs mots suscrits à la suite, on mettrait un `^` devant chaque mot suscrit. 

Si vous rencontrez des mots que vous n'arrivez pas à lire, faites ce que vous venez de faire : demander de l'aide. Et puis surtout ne laissez pas de blanc dans la ligne, il faut pouvoir les repérer. Vous pouvez mettre quelque chose comme "XXXX" le temps de trouver le mot à lire, mais notez bien quelles pages sont concernées, cela facilitera une relecture ensuite.

**Comment by alix-tz** [comment]
@CollapsarIsReal est-ce qu'il reste encore des questions à traiter dans cette issue ? Sinon, n'hésite pas à la clore.

**Comment by ElsaVK** [comment]
Non tout est bon pardon, je clos l'issue !
